/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package domain;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ChannelType { 
  mobile, store, web, video, email, app, kiosk, direct, other  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ChannelType\",\"namespace\":\"com.catalina.platform.avro\",\"symbols\":[\"mobile\",\"store\",\"web\",\"video\",\"email\",\"app\",\"kiosk\",\"direct\",\"other\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
