/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package domain;
@SuppressWarnings("all")
/** The type of event */
@org.apache.avro.specific.AvroGenerated
public enum EventType { 
  redemption, impression, click, checkout, media_delivery, visit, control, system, conversion, non_conversion, pin, threshold, pageview, screenview, item, social, exception, print, cart, wallet, goal, detection, notifications, download, clip  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"com.catalina.platform.avro\",\"doc\":\"The type of event\",\"symbols\":[\"redemption\",\"impression\",\"click\",\"checkout\",\"media_delivery\",\"visit\",\"control\",\"system\",\"conversion\",\"non_conversion\",\"pin\",\"threshold\",\"pageview\",\"screenview\",\"item\",\"social\",\"exception\",\"print\",\"cart\",\"wallet\",\"goal\",\"detection\",\"notifications\",\"download\",\"clip\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
